Третий проект диплом
xden15ka359x/Diplom_3 pull request #1
Opened 2023-10-02 19:46 UTC by xden15ka359x

2023-10-04 21:14 UTC, pavel-ulan requested changes
Так же как и предыдущие. Комплексно, работа хорошая, но есть пара моментов, которые очень режут глаз. Точно поправь локаторы, остальное опционально (хотя я бы попросил исправить все). Помимо этого забыл приложить аллюр-отчет (это одно из условий задания, работа с ТЗ это часть из твоих задач. пропускать требования ТЗ нельзя, насколько нелогичными они бы не казались.)
Поправь и жду исправленную работу =)

2023-10-04 21:14 UTC, pavel-ulan commented on src/main/java/org/praktikum/api/Constants.java
> +    }
**можно лучше**
та же ситуация

2023-10-04 21:14 UTC, pavel-ulan commented on src/main/java/org/praktikum/page_object_model/ConstructorModal.java
> +    private final By filingContainer = By.xpath("(//div)[4]/div[3]");
**надо исправить**
очень очень некрасивый локатор, состоящий из относительного пути с вложениями =/ (все 3-и последние, как ты понимаешь)

Старайся не использовать локаторы состоящие только из пути (не важно относительный/абсолютный). Как правило всегда можно подобрать другой, более читаемый, локатор. Такие локаторы плохо читаются, по ним непонятно, куда они указывают и если что-то меняется в верстке, то они ломаются и могут или никуда не вести или, что еще хуже, возвращать совершенно другой элемент.

2023-10-04 21:14 UTC, pavel-ulan commented on src/main/java/org/praktikum/page_object_model/PersonalAccountPage.java
> +    public LoginPage logOutUser() {
**можно лучше**
ты где-то используешь аннотации Step, где-то нет. Лучше или использовать везде где надо или не использовать совсем. т.к. это не только ухудшает "читабельность" кода, но и может заафектить формирование отчета в Аллюре

2023-10-04 21:14 UTC, pavel-ulan commented on src/test/java/org/praktikum/TestPattern.java
> +                throw new RuntimeException("Error: WebDriver not found");
**отлично**
проброс исключения, это клево, молодец =)

2023-10-04 21:14 UTC, pavel-ulan commented on src/test/java/org/praktikum/login/LoginTest.java
> +                {"https://stellarburgers.nomoreparties.site/forgot-password", "//a[contains(text(),'Войти')]"}
Решение интересное. Я бы сказал спорное, т.к. это не совсем то, что принято параметризовывать, но молодец, что заморочился и реализовал (причем вполне неплохо).
Но я бы советовал подходить к параметризации с осторожностью. Когда это разные наборы тестовых данных, тогда это бесспорно хорошее решение. 
Но тут это разный user flow...

2023-10-04 21:14 UTC, pavel-ulan commented on src/test/java/org/praktikum/transitions/ConstructorTest.java
> +        Assert.assertTrue(constructorModal.getElementClass(constructorModal.getFilingContainer()).contains("tab_tab_type_current__2BEPc"));
**можно лучше**
проверку на "tab_tab_type_current__2BEPc" стоило вынести в степы.
в тестовых классах не должно быть локаторов/частей локаторов/аттрибутов элемента и т.п. Все это описывается или в PO или в классе шагов, если он отдельный от PO. В тестовых методах должна происходить работа с методами, не более

2023-10-05 08:17 UTC, xden15ka359x commented on src/main/java/org/praktikum/page_object_model/PersonalAccountPage.java
> +    public LoginPage logOutUser() {
убрал

2023-10-05 08:22 UTC, xden15ka359x commented on src/test/java/org/praktikum/login/LoginTest.java
> +                {"https://stellarburgers.nomoreparties.site/forgot-password", "//a[contains(text(),'Войти')]"}
Спасибо! Я учту это на будущее. В данном кейсе я решил сделать параметризацию, тк по большей части функционал проверяет только переходы из какого-то определённого раздела на страницу логина, а сам функционал входа в систему всего однообразен и то из какого раздела мы попали на страницу логина никак не влияет на сам вход пользователя в систему

2023-10-05 17:54 UTC, xden15ka359x commented on src/test/java/org/praktikum/TestPattern.java
> +                throw new RuntimeException("Error: WebDriver not found");
Спасибо!

2023-10-06 18:19 UTC, pavel-ulan approved these changes
Гут. Отчет хороший, исправления так же огонь 👍

2023-10-07 08:00 UTC, merged